#include "web.h"

const char index_html[] = "\n"
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <title>ESP32 WiFi Configuration</title>\n"
"    <script>\n"
"        async function loadWiFiStatus() {\n"
"            try {\n"
"                const response = await fetch('/wifi_status');\n"
"                const status = await response.json();\n"
"                document.getElementById('status_mode').textContent = status.mode;\n"
"                document.getElementById('status_ssid').textContent = status.ssid || 'Not connected';\n"
"                document.getElementById('status_ip').textContent = status.ip || '-';\n"
"                document.getElementById('status_connected').textContent = status.connected ? 'Yes' : 'No';\n"
"            } catch (e) {\n"
"                console.error('Error loading status', e);\n"
"            }\n"
"        }\n"
"\n"
"        async function loadNetworks() {\n"
"            try {\n"
"                const response = await fetch('/wifi_scan');\n"
"                const data = await response.json();\n"
"                const select = document.getElementById('ssid_select');\n"
"                select.innerHTML = '<option value=\"\">Enter SSID manually</option>';\n"
"                data.forEach(network => {\n"
"                    const option = document.createElement('option');\n"
"                    option.value = network;\n"
"                    option.text = network;\n"
"                    select.appendChild(option);\n"
"                });\n"
"            } catch (e) {\n"
"                console.error('Error loading networks', e);\n"
"            }\n"
"        }\n"
"\n"
"        function updateSSIDField() {\n"
"            const select = document.getElementById('ssid_select');\n"
"            const ssidInput = document.getElementById('ssid_input');\n"
"            if (select.value !== '') {\n"
"                ssidInput.value = select.value;\n"
"            }\n"
"        }\n"
"\n"
"        async function resetWiFi() {\n"
"            if (confirm('Do you really want to delete the saved WiFi credentials?')) {\n"
"                await fetch('/wifi_reset', { method: 'POST' });\n"
"                alert('Credentials deleted. The device will restart in Access Point mode.');\n"
"                location.reload();\n"
"            }\n"
"        }\n"
"\n"
"        window.onload = function() {\n"
"            loadWiFiStatus();\n"
"            loadNetworks();\n"
"        };\n"
"    </script>\n"
"</head>\n"
"<body>\n"
"    <h1>ESP32 WiFi Configuration</h1>\n"
"\n"
"    <fieldset>\n"
"        <legend>Status</legend>\n"
"        <p>Mode: <span id=\"status_mode\">-</span></p>\n"
"        <p>SSID: <span id=\"status_ssid\">-</span></p>\n"
"        <p>IP address: <span id=\"status_ip\">-</span></p>\n"
"        <p>Connected: <span id=\"status_connected\">-</span></p>\n"
"    </fieldset>\n"
"\n"
"    <h2>Select or enter WiFi network</h2>\n"
"    <form method=\"POST\" action=\"/wifi\">\n"
"        <label for=\"ssid_select\">Detected networks:</label><br>\n"
"        <select id=\"ssid_select\" onchange=\"updateSSIDField()\"></select><br><br>\n"
"\n"
"        <label for=\"ssid_input\">SSID:</label><br>\n"
"        <input type=\"text\" id=\"ssid_input\" name=\"ssid\"><br><br>\n"
"\n"
"        <label for=\"password\">Password:</label><br>\n"
"        <input type=\"password\" name=\"password\"><br><br>\n"
"\n"
"        <button type=\"submit\">Connect</button>\n"
"    </form>\n"
"\n"
"    <br>\n"
"    <button onclick=\"resetWiFi()\">Reset credentials</button>\n"
"</body>\n"
"</html>\n"
"";
